### ISSUE TITLE
String compression

### ISSUE THREAD

**Issue by rurban** [msgpack/msgpack#115]
There was some talk about string compression or overall frame compression.
With zlib or Snappy.

I detected this simple library  https://github.com/antirez/smaz which compresses even very short strings efficiently. 
Smaz is able to compress even strings of two or three bytes.

**Comment by ygoe** [comment]
Is there still any interest in this? I'm thinking about using MessagePack as the communication protocol of a distributed system. Still evaluating options and frameworks but may end up writing my own.

I'd imagine string compression more on the connection level than for individual messages. A string would not be sent as-is every single time, but reused from a dictionary that is built up as it sees strings being sent. The sender could decide which strings appear most often and assign and unassign string aliases for them. These would be separate "types". The receiver would follow these assignments and transparently replace these short aliases with the corresponding string from the dictionary.

It's probably hard to implement on top of MessagePack so it should be implemented directly in the MessagePack serializer and deserializer. That thing would then have a state, which it doesn't have right now. The dictionary is reset for any new connection, of course.

We'd just need to define a protocol for that. Since most byte codes are already assigned (except 0xC1), it's probably hard to add without breaking changes. Sender and receiver could negotiate supporting this feature and would need to agree on using it.

That's my idea of how this can be done. If you send the same strings over and over again (like in a fixed data structure), you'd save a ton of space for all the names, and maybe even some values, without the need to give up the descriptive and flexible map structure.

**Comment by rurban** [comment]
Check out my smaz branch. It was slower, so we abandoned it.
