### ISSUE TITLE
Can the spec document be given a version?

### ISSUE THREAD

**Issue by cforger** [msgpack/msgpack#162]
Hello,

 Thanks for your work on MessagePack.

 While trying to figure out what msgpack libraries are compatible (between Python and JavaScript for example), I find it rather difficult because this document does not have a version on it.

 The messagepack.org site mentions v5 when it links here, but I don't see that on the document. 

 Without a clearly defined version variable in the specification document, you can't look at different source libraries and know that they will support 'Version 3' of the msgpack spec, etc.

 Additionally, a changelog would be very useful - There doesn't seem to be much history here, so when I look at a library that is 3 years old, I can't find what spec they were writing to conform to, which adds to my work to update that library. 

 Thanks.

**Comment by cforger** [comment]
Thought I'd check in a year later - Sad to see it's still open, but happy to see others taking up the cause.

It's such a simple thing, but oh so useful. 

This is a major hurdle for adoption for anyone wanting to use MsgPack across different languages.  I'm sure there are lots who are just giving up, and going back to JSON or BSON, because who has time to try and figure out where each language implementation left off in applying the specification?

**Comment by kuenishi** [comment]
Discussion is going on at #195.

If you wonder wether new spec is supported at the library of your language, it'd be good to open an issue at that repository and ask questions. That is usually because library maintainer is not good at documentation, stating things, or maintainers are not well organized. ... please ask. I think for C library, which looks like what you care, [the new spec was introduced at 0.5.8](https://github.com/msgpack/msgpack-c/releases/tag/cpp-0.5.8).
