### ISSUE TITLE
Disambiguate use of signed int formats

### ISSUE THREAD

**Issue by kostja** [msgpack/msgpack#164]
There is a range of cases when use of signed int format codes overlaps with unsigned int codes, for the positive part of the range.

The spec says nothing about it, but all the major implementations never use signed format codes for positive values or 0. 

Yet sometimes it can be beneficiary:
- to preserve the original host language data type in schema-less conversion
- to simplify packing of certain special cases.

The spec should make it clear whether an implementation should or should not use signed integer format codes for positive ranges, and if it should, then in what case.

**Comment by philhofer** [comment]
+1

I would be in favor of amending the spec to clarify that signed integers should be encoded as... signed integers. (The only reason unsigned integers are of any benefit in the spec in the first place is to support values between `(1<<63)-1` and `(1<<64)-1`, which some languages do not support natively in the first place.) I'd rather the types be treated as strictly incompatible whenever possible, because you need 65+bit integers to express the union of all possible (`int`, `uint`) values.

For instance, Ruby `fixnum` values are always 1 bit less than a machine word, so it will never have a value that needs to take the `uint64` storage class. (Conversely, `bignum` probably won't fit in *any* messagepack encoding.) In JavaScript, numbers are *always* just IEEE-754 floats, so, again, the language isn't even capable of expressing a value that would require `uint` storage.

**Comment by thinxer** [comment]
@frsyuki What do you say? Let's just make it clear in the spec whether we should pack positive signed int as unsigned.

Currently I'm trying to communicate between msgpack-c and tinylib/msgp. It is annoying that msgp won't accept the message encoded by msgpack-c.

**Comment by redboltz** [comment]
I've just wrote the PR for msgpack-c.

https://github.com/msgpack/msgpack-c/pull/250

Then I got some observation about this issue.
I think that reflecting signed/unsigend information from the C/C++ to msgpack format is not so good idea. So I will reject my pull request.

Let me describe the reason.

Here is a mapping table between value ranges and msgpack formats:

source value range     |msgpack format 
-----------------------|----------------
[  (1<<63) ,  (1<<64) )|uint64         
[  (1<<32) ,  (1<<63) )|uint64 or int64
[  (1<<31) ,  (1<<32) )|uint32         
[  (1<<16) ,  (1<<31) )|uint32 or int32
[  (1<<15) ,  (1<<16) )|uint16         
[  (1<< 8) ,  (1<<15) )|uint16 or int16
[  (1<< 7) ,  (1<< 8) )|uint8          
[   0      ,  (1<< 7) )|positive fixint
[ -(1<< 5) ,   0      )|negative fixint
[ -(1<< 7) , -(1<< 5) )|int8           
[ -(1<<15) , -(1<< 7) )|int16          
[ -(1<<31) , -(1<<15) )|int32          
[ -(1<<64) , -(1<<31) )|int64          

msgpack specification said that:

> If an object can be represented in multiple possible output formats, serializers SHOULD use the format which represents the data in the smallest number of bytes.

I think that it is reasonable because minimizing the serialized data size is one of major goal of the msgpack.

When we use int64_t in the C/C++, the value is serialized to uint family in the following case:

source value range     |msgpack format 
-----------------------|----------------
[  (1<<31) ,  (1<<32) )|uint32         
[  (1<<15) ,  (1<<16) )|uint16         

If we want to preserve the signed/unsiged information, we have to use bigger data format.
 e.g.) int64, int32

It is inefficient, so msgpack specification doen't allow it.


In the following case, I, one of the library implementer, can choose uint or int.

source value range     |msgpack format 
-----------------------|----------------
[  (1<<16) ,  (1<<31) )|uint32 or int32
[  (1<< 8) ,  (1<<15) )|uint16 or int16

When I choose uint, the implementation is simpler than int. I can eliminate one if branch. It makes a little faster code that using int.

When I choose int, the range and format mapping would be as follows:

source value range     |msgpack format 
-----------------------|----------------
[  (1<<32) ,  (1<<63) )|int64
[  (1<<31) ,  (1<<32) )|uint32         
[  (1<<16) ,  (1<<31) )|int32
[  (1<<15) ,  (1<<16) )|uint16         
[  (1<< 8) ,  (1<<15) )|int16
[  (1<< 7) ,  (1<< 8) )|uint8          
[   0      ,  (1<< 7) )|positive fixint

Hmm... the library sometimes preserve a singed/unsiged information, and sometimes not.

Finally, I started thinking that we shouldn't depends on the singed/unsiged information in the message pack format. We should treat it as a blackbox that can convert to signed/unsigned programming language types.

**Comment by kostja** [comment]
So what is your conclusiion? My suggestion is to only use INT formats for negative value range, for example, in the table above, never use int* formats. This will make it unambiguous. As long as the spec doesn't specify exactly one format for one value range, different packers/libraries may use different formats, so one stil can not rely on a particular format being used, but only has to account for an increased mess.

**Comment by redboltz** [comment]
Hi @kostja. My sonclusion is the same as yours. 
Using INT formats only for negative value range has the following advantage:

1. Eliminate if-branch.
1. Easier to understand and easier to debug. (When we monitor the serialized byte stream.)

The msgpack-c is implemented so. I will reject https://github.com/msgpack/msgpack-c/pull/250
Of course, msgpack-c can deserialize (convert) from INT and UINT to any integer types in C/C++ as long as the types have enough range to represent the value.

**Comment by kostja** [comment]
Thank you. Even if the spec does not define it, it could highlight the issue, so that implementors are aware of it. Otherwise the temptation to use format codes as type qualifiers, and thus carry additional type information in the stream can be high, and full ramifications not obvious until the first interoperability problem  with third-party encoders arises.
