### ISSUE TITLE
Best way to append multiple messages to file

### ISSUE THREAD

**Issue by espoal** [msgpack/msgpack#321]
I'm saving messages to disk, and I was wondering if there is a way to append multiple messages to the same, something like NDJSON for messagepack.

In NDJSON we use the property that newline is an invalid character. Is there an invalid byte sequence in msgpack? How could I delimit multipel messages?

Otherwise is there any better way?

I would like to avoid to parse and rewrite because the message list is a log.

**Comment by markusschaber** [comment]
While 0xc1 is an invalid "opcode", it may well appear within payload, so there's no such thing as an "invalid character". This makes it hard to synchronize from a random position within the stream. But if you just need "Append at the end" and "Read from the beginning", the solution could be straight forward.

If your messages have a fixed number of members (or you can otherwise determine the end of a message while parsing), you can just concatenate the messages. Alternatively, you could "wrap" each message in the payload of a MessagePack "bin" tag (byte array), so you know how long the message is without parsing it. Both approaches will allow you append Messages ot the end, and to read the stream from the beginning, the second allows for easier skipping of messages you're not interested in.

Maybe some streaming archive format like tar could also help, or if you want it fancy, go sqlite.

**Comment by espoal** [comment]
> This makes it hard to synchronize from a random position within the stream.

thanks @markusschaber , you confirmed what I thought.
